project:
  type: website

website:
  title: "GenAI Prompts for Literature Reviews"
  site-url: https://fs-ise.github.io/gen-ai-lr-prompts/
  repo-url: https://github.com/fs-ise/gen-ai-lr-prompts
  repo-actions: [edit, issue]
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: contributing.qmd
        text: Contributing
      - about.qmd
      - text: '{{< iconify octicon:mark-github-16 title="GitHub" label="GitHub" >}}'
        href: "https://github.com/fs-ise/gen-ai-lr-prompts"

  sidebar:
    - title: "Prompt Library"
      contents:
        - index.qmd
        - problem_formulation.qmd
        - search.qmd
        - screen.qmd
        - quality_assessment.qmd
        - data_extraction.qmd
        - data_analysis.qmd

format:
  html:
    grid:
      body-width: 1000px
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    smooth-scroll: true

extensions:
  iconify:
    style: "color: #002EFF;"
